# Generated by Django 4.0.3 on 2022-04-08 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_user_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
